### ISSUE TITLE
很容易GG吧

### ISSUE THREAD

**Issue by sephilex** [SenhLinsh/PriceAnalysisAssistant#1]
我去年也上架过一款类似的应用，也是靠着解析商品id进行下一步解析，但淘宝这半年来的淘口令都是没有链接的，只有淘口令，这近两个月才又恢复了，如果你有解析淘口令的方法，麻烦告诉我一声，邮箱是sephilex@gmail.com

**Comment by SenhLinsh** [comment]
没事啊，及时更新就好了，不过没办法接入他们专用的接口确实实现起来挺麻烦的，所以也不打算推广，目前也就自己在用，也算凑合。刚开始的时候解析淘口令确实没有什么办法，后来淘口令包含链接了，只要访问链接获取网页源数据在正则匹配就可以找到商品 Id 了。
